version: '3.7'

services:
  server:
    container_name: server
    build:
      context: ./
      target: dev
    restart: unless-stopped
    # command: npm run pm2 -- debug 0.0.0.0:9229
    # command: npm run dist
    # command: npm run dist
    command: npm run start:dev
    ports:
      - 3000:3000
      - 9229:9229
    env_file:
      - .env
    environment:
      - IN_CONTAINER=true
      # - DEBUG=*
      - PORT=3000
      - DATABASE_URL=postgresql://dohan:passwd@pg:5432/stackfolio?schema=public
    #   - G_MAIL_ID=${G_MAIL_ID}
    #   - G_MAIL_CLIENT_ID=${G_MAIL_CLIENT_ID}
    #   - G_MAIL_CLIENT_SECRET=${G_MAIL_CLIENT_SECRET}
    #   - G_MAIL_REFRESH_TOKEN=${G_MAIL_REFRESH_TOKEN}
    # Connection URL: postgresql://USER:PASSWORD@HOST:PORT/DATABASE?schema=SCHEMA
    volumes:
      - ./:/app:delegated
      - /app/node_modules
    depends_on:
      - pg
        # condition: service_healthy

  pg:
    container_name: pg
    image: postgres:13.1
    restart: always
    environment:
      - POSTGRES_USER=dohan
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_DB=stackfolio
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/1-init.sql
    ports:
      - '5432:5432'
    healthcheck:
      test: pg_isready -h 127.0.0.1
  nginx:
    # image: nginx
    # image: ehgks0000/stackfolio-nginx
    build:
      context: ./nginx
    container_name: proxy
    ports:
      - '80:80'
    # volumes:
    # /etc/nginx/conf.d/default.conf
    # - ./default.conf:/etc/nginx/conf.d/default.conf
    restart: 'unless-stopped'

  # pgAdmin:
  #   container_name: pgadmin_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=dohan@pgadmin.com
  #     - PGADMIN_DEFAULT_PASSWORD=passwd
  #     - PGADMIN_LISTEN_PORT=80
  #   ports:
  #     - '8080:80'
  #   volumes:
  #     - ./pgadmin/data:/var/lib/pgadmin
  #   depends_on:
  #     - pg
  #   links:
  #     - 'pg:pgsql-server'
