version: '3.7'

services:
  server:
    build:
      context: ./
      target: dev
    restart: unless-stopped
    command: npm run start:dev
    ports:
      - '3000:3000'
    environment:
      - IN_CONTAINER=true
      - PORT=3000
      - DATABASE_URL=postgresql://dohan:passwd@pg:5432/stackfolio?schema=public
      # Connection URL: postgresql://USER:PASSWORD@HOST:PORT/DATABASE?schema=SCHEMA
    volumes:
      - ./:/app:delegated
      - /app/node_modules
    depends_on:
      pg:
        condition: service_healthy

  pg:
    image: postgres:13.1
    restart: always
    environment:
      - POSTGRES_USER=dohan
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_DB=stackfolio
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/1-init.sql
    ports:
      - '5432:5432'
    healthcheck:
      test: pg_isready -h 127.0.0.1

  # pgAdmin:
  #   container_name: pgadmin_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=dohan@pgadmin.com
  #     - PGADMIN_DEFAULT_PASSWORD=passwd
  #     - PGADMIN_LISTEN_PORT=80
  #   ports:
  #     - '8080:80'
  #   volumes:
  #     - ./pgadmin/data:/var/lib/pgadmin
  #   depends_on:
  #     - pg
  #   links:
  #     - 'pg:pgsql-server'
